# =========================
# 🔐 Secret MySQL
# =========================
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  DB_USERNAME: root
  DB_PASSWORD: rootpassword
---
# =========================
# ⚙️ ConfigMap Spring Boot
# =========================
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/studentdb?createDatabaseIfNotExist=true
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
  SERVER_PORT: "8089"
  SERVER_SERVLET_CONTEXT_PATH: /student
---
# =========================
# 🚀 Deployment Spring Boot
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
        - name: student-management
          image: amine0019/student-management-backend:latest
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
            - name: SPRING_JPA_SHOW_SQL
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: SPRING_JPA_SHOW_SQL
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: SERVER_PORT
            - name: SERVER_SERVLET_CONTEXT_PATH
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: SERVER_SERVLET_CONTEXT_PATH
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
---
# =========================
# 🌐 Service NodePort
# =========================
apiVersion: v1
kind: Service
metadata:
  name: student-management-service
spec:
  type: NodePort
  selector:
    app: student-management
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30089